### PR TITLE
fix: upsert walk was not checking for nils

### LINKED ISSUE #50: [GSP-7] Walk method panics for UPSERT statement
* This is the root cause of [JSTC-15](https://linear.app/tableland/issue/JSTC-15/upsert-parsing-error-causes-shell-to-crash)
* The `wasm-sqlparser` makes use of of the `Walk` helper method that walks down the whole AST. There's a problem in that "walking" for the following UPSERT statement: `insert into test_31337_2 values (1,'a') on conflict do update set val='new';` The problem is that that statement has no [target](https://www.sqlite.org/lang_UPSERT.html). And the `walkSubtree` method was not accounting for that.

<sub>From [SyncLinear.com](https://synclinear.com) | [GSP-7](https://linear.app/tableland/issue/GSP-7/walk-method-panics-for-upsert-statement)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [GSP-7](https://linear.app/tableland/issue/GSP-7/walk-method-panics-for-upsert-statement)</sub>

### PR DESCRIPTION
**Pull request by brunocalza**
# Summary

Closes #50 

cc @awmuncy

### CODE REVIEW

File: helpers_test.go [hunk 1]
```diff
@@ -111,3 +111,19 @@ func TestValidateTargetTable(t *testing.T) {
 		require.Equal(t, "t_2_1__1", validTable.Name())
 	})
 }
+
```
Comment (brunocalza) [inline helpers_test.go:114]: Added a test for statement that was panicking to make sure the problem was solved

File: ast.go [hunk 2]
```diff
@@ -1882,7 +1882,17 @@ func (node *OnConflictClause) walkSubtree(visit Visit) error {
 	if node == nil {
 		return nil
 	}
-	return Walk(visit, node.Target.Columns, node.Target.Where, node.DoUpdate.Exprs, node.DoUpdate.Where)
+
```
Comment (brunocalza) [inline ast.go:1885]: `Target` and `DoUpdate` can be `nil`. Gotta check for that

Comment (avichalp) [reply ast.go:1885]: 👍

**Review by avichalp — APPROVED** [review]
